### ISSUE TITLE
Override STAC_VERSION?

### ISSUE THREAD

**Issue by mojodna** [sat-utils/sat-stac#33]
https://github.com/sat-utils/sat-stac/blob/8963f37d3e8e3836654980871d8354435d8eeb38/satstac/catalog.py#L8 specifies the STAC version that sat-stac is compatible with. However, in some cases, users may wish to override this, e.g. when a minor STAC version has been released that sat-stac generates valid output for but does not yet explicitly support.

**Comment by matthewhanson** [comment]
Good thinking @mojodna, will add for next version
