### ISSUE TITLE
Incorrect Windows paths while downloading

### ISSUE THREAD

**Issue by NosyParker** [sat-utils/sat-stac#51]
When trying to pass _absolute windows path_ to `item.download()` like this one:  `C:/custom/path`  
it becomes to  `C_colon_/custom/path` due to `item.substitute()`  calls `replace(':', '_colon_')` which works fine on path templates but full path is getting wrong.

**Comment by matthewhanson** [comment]
This has been fixed on develop and will be released with 0.4.0 in the next few days.
