### ISSUE TITLE
Cannot import Items from satstac

### ISSUE THREAD

**Issue by XingongLi** [sat-utils/sat-stac#58]
When I tried to the following line:
from satstac import Items

I got:
ImportError: cannot import name 'Items' from 'satstac' (/srv/conda/envs/notebook/lib/python3.7/site-packages/satstac/__init__.py)

Why and how to fix it?

**Comment by matthewhanson** [comment]
In the most recent versions of satstac, it is now `ItemCollection` instead of `Items`.

I think the notebook examples need to be updated
