### ISSUE TITLE
path_template

### ISSUE THREAD

**Issue by XingongLi** [sat-utils/sat-stac#59]
When I tried the following cell (#15) in tutorial1 notebook:

path = '${landsat:path}/${landsat:row}'
filename = '${date}/${id}.json'

collection.add_item(item, path_template=path, filename_template=filename)
print('Item filename: ', item.filename)

print('\n**Item links**')
pp.pprint(item._data['links'])

I got:
TypeError: add_item() got an unexpected keyword argument 'path_template'

What went wrong and how can I fix it?

**Comment by matthewhanson** [comment]
Hello @XingongLi 
It seems like a mismatch between the version example and what you have installed.

What version of satstac are you using?

**Comment by XingongLi** [comment]
sat-stac                  0.3.1
