### ISSUE TITLE
BBOX input is off

### ISSUE THREAD

**Issue by cholmes** [sat-utils/sat-stac#66]
@matthewhanson - not sure if this is the right repo for the element84 earth search server, but see https://github.com/radiantearth/stac-api-spec/issues/47

It looks like it expects /search?bbox=[4,4,5,5] format, while all the rest are /search?bbox=4,4,5,5

**Comment by matthewhanson** [comment]
It would be under stac-server: https://github.com/stac-utils/stac-server/issues

Thanks, I saw that issue and promptly forgot about it.    I'm overdue on fixing the /collections endpoint response too.
